version: '3'

services:
  nginx:
    image: nginx:1.19.2-alpine-perl
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - nginx-www-build:/var/www
      - nginx-letsencrypt-certs:/etc/letsencrypt
      - nginx-letsencrypt-data:/var/lib/letsencrypt
      - nginx-log:/var/log/nginx/
volumes:
  nginx-www-build:
