version: '3'

services:
  sourcedb:
    image: zworkroman/sshcli
    restart: unless-stopped
    environment:
      - SSHCLI_SSH_ID_ACCESS=${SSHCLI_SSH_ID_ACCESS:-}
      - SSHCLI_SSH_CONFIG=${SSHCLI_SSH_CONFIG:-}
    ports:
      - 3307:3306
    command: [ "ssh", "-NL", "0.0.0.0:3306:${SOURCEDB_HOST:-localhost}:${SOURCEDB_HOST_PORT:-3306}", "${SOURCEDB_PROXY_HOST}" ]
  db:
    image: mysql:8.0.21
    restart: unless-stopped
    depends_on:
      - sourcedb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    command: --federated
    env_file: .mysql.env
    ports:
      - 3306:3306
    volumes:
      - db-conf:/etc/mysql/conf.d
      - db-var:/var/lib/mysql
      - db-log:/var/log/mysql
    cap_add:
      - SYS_NICE
  api:
    depends_on:
      - db
    image: zworkroman/horse24-api
    restart: unless-stopped
    env_file:
      - .mysql.env
      - .api.env
  fe:
    depends_on:
      - api
    image: zworkroman/horse24-fe
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - fe-letsencrypt-certs:/etc/letsencrypt
      - fe-letsencrypt-data:/var/lib/letsencrypt
      - fe-log:/var/log/nginx/
  cert:
    image: certbot/certbot
    restart: "no"
    volumes:
      - fe-letsencrypt-certs:/etc/letsencrypt
      - fe-letsencrypt-data:/var/lib/letsencrypt
volumes:
  db-conf:
  db-var:
  db-log:
  fe-letsencrypt-certs:
  fe-letsencrypt-data:
  fe-log:
